services:
  - type: web
    name: wais-mbti
    env: python
    plan: free
    buildCommand: ""  
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false  # This prevents it from being stored in the YAML file
